### ISSUE TITLE
Images won't display after forking and publishing

### ISSUE THREAD

**Issue by MCMaurer** [ramswaroop/photography#6]
Hey there,

I really love your site design and decided to give it a shot. I forked the repo and deleted the CNAME file so it would use https://mcmaurer.github.io/photography/ to publish, but when I go to the published site, neither the thumbs or full images display. I tried replacing the images with my own, using gulp to generate the fulls and thumbs, but the same problem occurred. Hoping you can help me identify the issue. Thanks!

**Comment by ramswaroop** [comment]
Can you try changing the `url` property in `_config.yml` file to `https://mcmaurer.github.io/photography/` ?

**Comment by MCMaurer** [comment]
Just tried that, and the site looks the same.

**Comment by MCMaurer** [comment]
I figured it out! Jekyll has a problem with image names that have an underscore in them, and for some reason Lightroom included an underscore in all my image names. Thanks!

**Comment by ramswaroop** [comment]
I don't think underscore is the issue, I have underscores in all the images in my example.

**Comment by MCMaurer** [comment]
They were at the start of the filename, such as _10822.jpg, I think that may have been the issue

**Comment by ramswaroop** [comment]
Mmm weird issue, if this is really the case then it should be fixed at the jekyll end.

**Comment by MCMaurer** [comment]
Let me double check later today and I'll let you know if that is the case. The stack overflow I saw suggested it was indeed a Jekyll issue

**Comment by ramswaroop** [comment]
Can you please post the SOF link here?

**Comment by MCMaurer** [comment]
Ok I was a little premature on this one. It worked for a basic Lightroom gallery that had a similar problem, but it looks like I'm still having the problem here. This is the page I looked at that gave me the idea for the other site: https://stackoverflow.com/questions/18015055/why-arent-my-images-showing-up-on-my-github-page

Looks like I still can't get images to show up at mcmaurer.github.io/photography/

**Comment by ramswaroop** [comment]
Can you please use `/photography` as the value for `baseurl` field in `_config.yml` file and let me know if it works?
